site_name: Communications Documentation
theme:
   name: material
  #  font: 
  #   text: Merriweather Sans
  #   code: Red Hat Mono
  #  palette:
  #   - scheme: default
  #     toggle:
  #       name: Light mode
  #     primary: blue
  #     accent: deep orange

   features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
   

nav:
  - Home: index.md
  - Website Proposal: week01.md
  - Design Processes: week02.md
  - User Personas: week03.md
  - Ideation: week04.md